### ISSUE TITLE
Add a no args constructor

### ISSUE THREAD

**Issue by campbellbartlett** [OlliTietavainenVaadin/clipboardhelper#3]
Hi @OlliTietavainenVaadin,
Love this component! It's been really helpful for us in our project.

Do you think it would benefit with a no args constructor? We often find we want to construct the wrapper before we have the content to be copied, especially when we are fetching data from a backend via a web request which may take some time to load.

I've opened a PR with the changes, let me know what you think.

Cheers!

**Comment by OlliTietavainenVaadin** [comment]
Looka like a good idea, I'll try to find some tine to publish a new version soon. Thanks!

**Comment by OlliTietavainenVaadin** [comment]
Uploaded 1.1 with a parameterless constructor.

**Comment by campbellbartlett** [comment]
Awesome, thanks!
